repos:
  - repo: local
    hooks:
      # - id: backend-ruff
      #   name: Run ruff for backend
      #   entry: ruff check src
      #   language: system
      #   pass_filenames: false
      - id: backend-black-check
        name: Check code formatting with black for backend
        entry: black --check src
        language: system
        pass_filenames: false
