services:
  db:
    image: postgres:16
    container_name: transaction-flask-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: src/Dockerfile
      target: prod
    container_name: transaction-flask-app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://username:password@db:5432/db
      - FLASK_APP=src.app:create_app()
      - FLASK_ENV=production
      - PYTHON_PATH=/app/src
    depends_on:
      - db
    entrypoint: ["bash", "-c", "./entrypoint.sh gunicorn -w 4 -b 0.0.0.0:5000 'app:create_app()'"]

volumes:
  db_data:
