services:
  app:
    build:
      target: dev
    environment:
      - FLASK_ENV=development
    volumes:
      - ./src:/app/src
    entrypoint: ["sh", "-c", "./wait-for-it.sh db:5432 -- python -m persistence.init_db && flask run --reload"]
