services:
  app:
    build:
      target: dev
      dockerfile: src/Dockerfile.dev
    environment:
      - FLASK_ENV=development
      - JAEGER_AGENT_HOST=jaeger
    volumes:
      - ./src:/app/src
    entrypoint: ["sh", "-c", "./entrypoint.sh flask run"]

  worker:
    build:
      target: dev
      dockerfile: src/Dockerfile.dev
    environment:
      - FLASK_ENV=development
      - JAEGER_AGENT_HOST=jaeger
    volumes:
      - ./src:/app/src
