"""Modify transactions table to include exchange rate, target_currency and converted_amount.

Revision ID: 8d39412f4165
Revises: 3dc081995e84
Create Date: 2024-09-01 10:45:53.392768

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d39412f4165"
down_revision: Union[str, None] = "3dc081995e84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("original_amount", sa.Float(), nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("original_currency", sa.String(), nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("converted_amount", sa.Float(), nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("target_currency", sa.String(), nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("exchange_rate", sa.Float(), nullable=True),
    )
    op.drop_column("transactions", "amount")
    op.drop_column("transactions", "currency")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "currency",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("transactions", "exchange_rate")
    op.drop_column("transactions", "target_currency")
    op.drop_column("transactions", "converted_amount")
    op.drop_column("transactions", "original_currency")
    op.drop_column("transactions", "original_amount")
    # ### end Alembic commands ###
