"""Rename EnrichedTransaction model for ProcessedTransaction model.

Revision ID: 8e7c94e350de
Revises: c1b900e83957
Create Date: 2024-09-03 14:39:19.903447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e7c94e350de"
down_revision: Union[str, None] = "c1b900e83957"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
