"""Add incoming transaction table for holding incoming transactions.

Revision ID: c1b900e83957
Revises: 8d39412f4165
Create Date: 2024-09-02 16:32:33.082091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1b900e83957"
down_revision: Union[str, None] = "8d39412f4165"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incoming_transactions",
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index(
        op.f("ix_incoming_transactions_transaction_id"),
        "incoming_transactions",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incoming_transactions_user_id"),
        "incoming_transactions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_incoming_transactions_user_id"),
        table_name="incoming_transactions",
    )
    op.drop_index(
        op.f("ix_incoming_transactions_transaction_id"),
        table_name="incoming_transactions",
    )
    op.drop_table("incoming_transactions")
    # ### end Alembic commands ###
