global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "flask"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:5000"]

  - job_name: "celery"
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:6543"]
