# Stage 1. Builder stage for development
FROM python:3.12-slim AS dev-builder

WORKDIR /app

RUN apt update && \
  apt install -y curl && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV PATH="/root/.local/bin:$PATH"

COPY pyproject.toml poetry.lock /app/


RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --with tracing,metrics,tests

# Stage 2. Development stage
FROM python:3.12-slim AS dev

WORKDIR /app

COPY --from=dev-builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=dev-builder /usr/local/bin /usr/local/bin

COPY src /app/src
COPY wait-for-it.sh entrypoint.sh alembic.ini pyproject.toml /app/

COPY prometheus/prometheus.yml /etc/prometheus/prometheus.yml
COPY grafana/provisioning  /etc/grafana/provisioning
COPY tests /app/tests

ENV PYTHONPATH=/app/src
ENV FLASK_APP=src/app.py
ENV FLASK_ENV=development
ENV FLASK_RUN_HOST=0.0.0.0
ENV PROMETHEUS_MULTIPROC_DIR=/var/cache/celery_prometheus

RUN mkdir -p $PROMETHEUS_MULTIPROC_DIR

EXPOSE 5000

CMD ["flask", "run"]
